[web]
10.10.20.20 ansible_user=rol3user ansible_port=2222

[docker_hosts]
10.10.20.30 ansible_user=rol3user

[proxy]
10.10.20.10 ansible_user=rol3user

[linux:children]
web
docker_hosts
proxy

[linux:vars]
ansible_python_interpreter=/usr/bin/python3
